# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.24
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Akretion
org_slug: akretion
rebel_module_groups: []
repo_description: Subcontractor Work Invoicing
repo_name: Subcontractor Work Invoicing
repo_slug: subcontractor
repo_website: https://github.com/akretion/subcontractor
use_pyproject_toml: false
use_ruff: true

