# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Akretion
org_slug: akretion
rebel_module_groups: []
repo_description: null
repo_name: Subcontractor Work Invoicing
repo_slug: subcontractor
repo_website: https://github.com/akretion/subcontractor
travis_apt_packages: []
travis_apt_sources: []

