
language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "Pre-Commit"
      python: 3.6
      install: pip install pre_commit
      script: pre-commit run --all

env:
  global:
  - VERSION="10.0" TESTS="1" LINT_CHECK="0"

  matrix:
  - TESTS="0" LINT_CHECK="1"
  - ODOO_REPO="OCA/OCB"
  - UNIT_TEST="1" ODOO_REPO="OCA/OCB"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev\nkeychain_key_dev = HRdthrkXp28SCHX0kmwOgIob-82N-w8zWoE_UsctE7E=' > ${HOME}/.openerp_serverrc
  - git clone https://github.com/akretion/akretion-quality-tools ${HOME}/akretion-quality-tools
  - export PATH=${HOME}/akretion-quality-tools/travis:${PATH}
  - travis_configure

script:
  - mv .isort.cfg .isoft.cfg.disabled # to avoid trouble with pylint odoo
  - travis_run_tests

after_success:
  - travis_after_tests_success
