from . import project_project
from . import project_task
from . import account_move
from . import account_move_line
from . import subcontractor_work
from . import account_analytic_line
from . import project_invoice_typology
from . import product_template
from . import res_company
from . import account_account
from . import res_partner
